<!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link rel="stylesheet" href="content.css">
     <?php 
        include '../head.php';
     ?>
     <title>Big data</title>
 </head>
 <body>
   <?php include '../menu.php'; ?>
   <main class="p-5 container">
       <article class="row">
       <section class="col-12 col-md-8">
            <div class="col-12 mx-auto">
            <h2 class="text-dark">Understanding Big Data and its Technologies </h2>
               <p class="lead text-dark">Learn the basics Big Data Analytics</p>
               <?php include 'author.php'; ?>
            </div>
            <figure class="post-img py-5">
                <img src="/projectAlpha/images/bigata-blog-image.jpg" class="img-fluid">
            </figure>
            <p>Data gathering&#8212;an age long tradition that
            influences some of the major decisions organizations have ever made.
             Decisions are predominantly made, not
            at the whims of leaders or CEOs, but through telling insights 
            and models harnessed from the analysis of the data gathered.
           
           </p>
           <p>That being said, It is very clear that data constitutes an 
               invaluable information assets to organizations&#8212; to 
               succeed and stay ahead of the game, business and organizations
               must vigorously pursue data gathering and analysis&#8212; a process 
               that has become overly cumbrous in recent years.
           </p>
           <p>
               Back in the days when data generated by organizations were just
               a few terrabyte, spreadsheet provided a convenient solutions for 
               managing data. But with the dawn of the technological age, spreadsheet
               became inadequate, as the advances in technology brought with it vast 
               increase in data generation. 
               </p>
               <p>Organizations were not just dealing with data anymore. To describe
               the overwhelming proliferation of data, the 
               term  "big data" was coined. spreadsheet had failed;
               It gave way to the familiar relational database&#8212; An architecture based 
               on a system of rows and columns. Information became all so easily 
               available&#8212; at the click of a mouse, there you go, everything you needed, 
               neatly placed in front of you; managing data wasn't
               just a lightening-quick operation, but also, an orderly exercise.
           </p>
           <p>
               While organizations enjoyed the robustness provided by the relational database
               system, data generation remained on the trajectory:
               driven by the advancement in technology, organizations were generating
               data at an unprecedented speed. The term "big data" was gaining
               traction. All of a sudden, the once out-of-the-box solution 
               provided by RDMS, became feeble and inefficient. The speed of 
               data generation had overwhelm the database system&#8212;it had failed to 
               scale
               as heterogeneous data continue to sweep-in in extreme speed.
           </p>
           <p>Big data analytics was the latest technological innovation&#8212;and it is
               now the driving force behind major technological advances(artificial
               intelligence and iot). Our
               traditional data processing method had failed miserably; The amount
               of data generated by organizations, kept swelling exponentially&#8212;
               even as I write this article, more data is been generated each day than in 
               the entire history of the human race.
           </p>
           <p> To make sense of the ever growing data, high performance 
               technologies were invented to store and analyze the data 
               in-real-time. Some of the solutions provided are: faster 
               processors, cheap abundant storage, cloud computing,
               hadoop.
           </p>
           <p> Now let's see how the term "big data" is defined,  and the 
               solutions employed today to deal with them.
           </p>
           <h3>What Big Data?</h3>
           <p>Different organizations have tried to define the term "big data" 
            in slightly different ways. Some of which are given below:</p>
           <p>According to the American IT and research Advisory firm Gartner Inc.,<br>
           <br><em>"Big Data is a high volume, high velocity and/or high variety
                information assets that demand cost effective, innovative forms
                of information processing that enable enhanced insights, decision
                making, and process automation."</em></p>

            <p>According to SAS,<br>
                <em>Big Data is a term that describe a large volume of data
                &#8212;both structured and unstructured-that inundates a 
                    business on a-day-to-day basis.
                </em>
            </p>
            <p>And Wikipedia has this to say about big data,<br>
                <em>
                   "Big Data is a term used to refer to the study and 
                   applications of data sets that are so big and complex 
                   that traditional data processing applications software
                   are inadequate to deal with them." 
                </em>
            </p>
            <p>No doubt, big data has become part of our lives; nearly
               every human endeavour today is driven by technology. 
               As we interacts with our friends 
               and loved ones in social media, or as the web of interconnected 
               devices communicating with one another through sensor and smart 
               metering in the IoT-enabled environment, we generate pools of data in the 
               process&#8212;data that we must harness, integrate and analyze in 
               near-real-time to discern patterns that will lead to better decision making.
            </p>
            <h2>But what makes big data so overwhelming? </h2>
            <figure class="pt-3">
                <img src="/projectAlpha/images/why-so-big-q.jpg">
                 class="img-rsp">
            </figure>
            <p> 
               When discussing big data, it's important that we classify big 
               data according to the triple Vs, which underline the complexity 
               of big data though some experts often add extra V or Vs, but 
               for simplicity, I will stick to the triple Vs.     
            <p>
            <p><strong>Volume:</strong> This refers to the rate at which data is 
               produced. The amount of data organizations have to deal with comes 
               from multiple sources, which includes: social media, machine-to-machine
                data via sensors, website users log info&#8212;which
                includes: click through rate, customer 
               conversion rate etc. These data comes in large volumes&#8212;and would undoubtedly
               pose serious challenge if traditional data processing method were to 
               be employed.
            </p>
            <p><strong>Velocity:</strong> Data generation today streams-in at enormous speed.
                These data need to be analyzed in near-real-time. 
                With high performance technologies like parallel processing and 
                clustering now available, integrating and
                analyzing these overwhelmingly high velocity data in real time now seems like a breeze.
                

            </p>
            <p><strong>Variety: </strong> Big data comes in different formats.
                 Big data could be structured, unstructured or semi- 
                structured. today's big data are typically constituted by videos, pictures,
                text files, emails, data from RFID tags etc.
           </p>
            <h3>Importance of dealing with big data</h3>
            <p>Big data when effectively analyze could leads to insightful
                decisions which can:
                <ul class="post-list-items">
                    <li>Lead to the development of new products
                        according to customers buying habits. And 
                        poorly performing products improved upon to satisfy user's
                        preferences.
                    </li>
                    <li>Root causes of failure can be determine and 
                        eliminated.
                    </li>
                    <li>Improved customer relationships and customer satisfaction
                         based on information gathered on customer orientation
                          and behavioral patterns.
                    </li>
                    <li>Calculates an entire risk portfolios in seconds.</li>
                </ul>
            </p>
            <h3>Dealing with Big Data</h3>
             <p> Big data has become a blessing in disguise to entrepreneur, rather
                than be overwhelm by their apparent complexities,
                these big data have become a massive asset to organizations&#8212;enabling
                them to easily  discern patterns, relationships and clues that where
                initially hidden, aptly guiding them to be more insightful in their
                decision making processes which have led to upswing in profitability.
         </p>
         <p>In integrating and analyzing big data, High performance analytic
             methods and tools that enhance big data usability and make its integration and analysis
             a snap includes: 
             <ul class="post-list-items">
                 <li>Cheap abundant storage</li>
                 <li>Faster processors</li>
                 <li>Affordable open source distributed big data platforms
                     such as Hadoop.
                 </li>
                 <li>Parallel processing, clustering, MPP, visualization,
                     large grid environments, high connectivity and high 
                     throughputs&#8212;Apache spark
                 </li>
                 <li>Cloud computing</li>
             </ul>
         </p>
         <h3>Application of Big Data</h3>
         <p>With the technological revolution taking place in the tech
             industry at the moment, Big data analytics couldn't be more
             important. Nearly every areas or field have witness at least one major 
             innovation in recent years. 
         </p>
         <p><strong>Manufacturing Industry. </strong> The manufacturing industry
        is highly data driven&#8212; machines are now increasingly been built with
         sensors for process automation&#8212; Data from RFIDs tags are generated
          at great speed and require urgent analysis to enable production
           optimization and cost reduction.
        </p>
        <p>
            <strong>Finance/Banking. </strong>
            Financial Institutions are well known to generate large volumes of 
            data&#8212;from customers information to transactions. Banks make 
            use of these information to improve their operations&#8212;as an example,
            collecting data on customer history can help prevent fraudulent 
            transactions: a mishap that would otherwise expose the bank to litigation 
            and financial sanction.
        </p> 
        <p><strong>Medicine. </strong>Medicine being a research intensive field, 
        experts need to 
        collect and analyze data from various areas. These data could be patient's
        treatment history, or data on the pattern of disease infestation and cases 
        can be analyzed, and could eventually lead to a breakthrough in finding a cure.    
        </p>
        <p><strong>Security/Policing. </strong>Big data analytics have uses well beyond
        business and marketing. Data collected from intelligence can be used to prevent
        crimes while bolstering defenses at the same time. Big data analytics tools can
         provide information that can be used to form strategies, guide planning in a 
         bid to identify and combat crime. 
        </p>
        <h3>Conclusion</h3>
        <p>Big data can be very overwhelming if not properly integrated&#8212;it
            comes in great speed, and in, varieties making the integration 
            an extremely complex process and&#8212;way beyond the scope of the traditional 
            data processing methods.
        </p>
        <p>With the current advances in technology&#8212;which is dominated by IoT, 
            artificial intelligence and blockchain technology, the volume of 
            data that inundates individuals and businesses on a daily basis is 
            showing no signs of slowing down. In fact, statistics has shown that the 
            volume of data will only continue to increase especially as we bask 
            in the infectious conveniences provided by the digital age.
        </p>
        <p>In dealing with the huge volume of data, high performance and highly 
           scalable technologies/platforms were built to integrate these 
           heterogeneous data structures. Some of them are Hadoop, grid computing,
            parallel processing and cheap abundant storage.
        </p>
        <p>
            Big data in all its complexities and abundance, in itself has no real value if not 
            efficiently integrated. On the other hand though, when fully harnessed, 
            it constitutes an invaluable information assets to organizations and 
            businesses from which unusual success can be achieved. 
        </p>
       
       </section>
       <aside class="col-12 col-md-3"></aside>
       </article>
   </main>
   <?php  include '../script.php'; ?>
   <?php include '../footer.php'; ?>
 </body>
 </html>